name: Build, lint and test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    uses: cloudscape-design/actions/.github/workflows/build-lint-test.yml@main
    secrets: inherit
